### ISSUE TITLE
can't download dataset

### ISSUE THREAD

**Issue by dingtom** [yongsen/SignFi#2]
i can't download the dataset by the url you provied , and i've tried use another browser and  it still not work. if there are another way to get the dataset?

**Comment by yongsen** [comment]
What error message did you get? Could you try to disable other extensions like adblocker? Some other people mentioned in another post that adblocker was causing some issues. I just have a try, and the url works for me.

**Comment by dingtom** [comment]
i've tried use IE browser it doesn't install any extensions, but i can't access the website.

**Comment by yongsen** [comment]
So you cannot open the download link, or you can open it but cannot download? And all the url links are not working for you?

**Comment by dingtom** [comment]
i cannot open the download link






------------------ 原始邮件 ------------------
发件人: "Yongsen Ma"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 中午11:07
收件人: "yongsen/SignFi"<SignFi@noreply.github.com>; 
抄送: "2524370217"<2524370217@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yongsen/SignFi] can't download dataset (#2)




So you cannot open the download link, or you can open it but cannot download? And all the url links are not working for you?

**Comment by yongsen** [comment]
What error message did you get?

**Comment by dingtom** [comment]
after i turn on the vpn i can access the website 



------------------ 原始邮件 ------------------
发件人: "Yongsen Ma"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 中午11:13
收件人: "yongsen/SignFi"<SignFi@noreply.github.com>; 
抄送: "2524370217"<2524370217@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yongsen/SignFi] can't download dataset (#2)




What error message did you get?

**Comment by yongsen** [comment]
OK. Maybe box.com is somehow blocked by your network.
