### ISSUE TITLE
What is "uplink" in "uplink CSI traces"?

### ISSUE THREAD

**Issue by SivaAndMe** [yongsen/SignFi#3]
What is the difference between "uplink CSI traces" and "downlink CSI traces"?  Which one of them is used for the experiments described in the paper?  [signfi_cnn_example.m](https://github.com/yongsen/SignFi/blob/master/signfi_cnn_example.m) mentions that the downlink CSI traces are used. Is it true with other environments like home and lab+home? I couldn't find any details regarding this in the paper. 

The above terms are mentioned in the README file:

> Segmented **downlink** CSI traces and ground truth labels for 276 sign words in the lab environment. There are 5,520 instances of 276 sign gestures performed by one user.
> Segmented **uplink** CSI traces and ground truth labels for 276 sign words in the lab environment. There are 5,520 instances of 276 sign gestures performed by one user.

Thanks.

**Comment by yongsen** [comment]
Uplink means Wi-Fi packets are sent from station (e.g. laptop) to Wi-Fi AP, and downlink means from AP to station. In the paper, only downlink CSIs were used.
